### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by poetaman** [shiyanhui/libcsp#13]
Website (implicit) is down, null, segafaulted. Also, is this project maintained?

What is the cost of coroutine? Can 8 coroutines run on 8 CPUs at the same time in multicore environment?

**Comment by yann-shi** [comment]
Figuring out why it's down. Yes, it's still be maintained. And yes, multiple coroutines can run in multiple cores parallelly.

**Comment by yann-shi** [comment]
Fixed. Please visit https://libcsp.dev.
