### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by dscottboggs** [shiyanhui/libcsp#4]
https://github.com/shiyanhui/libcsp/blob/ea0c5a41d7b518027019e7eaad7e575f7cc45d30/src/rbq.h#L249-L251

it looks like you meant to use `T` here, not `t`. I might be wrong on that though, using `t` will work too

**Comment by yann-shi** [comment]
No, it's not a bug.  Here `t` is the literal `t` character.

For example, the macro `csp_rbq_name(mm, t, id)` will be expanded to `csp_mmrbq_t_id`.

**Comment by dscottboggs** [comment]
Thanks for clarifying, I thought that might be the case.
