### ISSUE TITLE
Unable to install libcsp

### ISSUE THREAD

**Issue by brianoh** [shiyanhui/libcsp#6]
I’m not very familiar with Linux, and not very familiar with “C”, so perhaps the problem is caused by my unfamiliarity.

I believe that I followed the installation instructions, however I was unable to install libcsp. The following are the steps that I took. (No ./configure file) :

1. On Ubuntu 20.04 LTS.

2. I ran “sudo apt install gcc- ….” as per the instructions, and that completed OK.

3. I downloaded libcsp but there was no option for “.tar.gz”, so I used “.zip”, and extracted the download to libcsp-master.

4. I was unable to run ./configure because it is not in the libcsp directory. The directory contents are as follows:

```
drwxrwxr-x 2 brian brian 4096 Jul  7 16:39 benchmarks
-rw-rw-r-- 1 brian brian 2083 Jul  7 16:39 configure.ac
drwxrwxr-x 5 brian brian 4096 Jul  7 16:39 docs
drwxrwxr-x 2 brian brian 4096 Jul  7 16:39 examples
-rw-rw-r-- 1 brian brian 1023 Jul  7 16:39 LICENSE
-rw-rw-r-- 1 brian brian 2551 Jul  7 16:39 Makefile.am
drwxrwxr-x 2 brian brian 4096 Jul  7 16:39 plugin
-rw-rw-r-- 1 brian brian  493 Jul  7 16:39 README.md
drwxrwxr-x 2 brian brian 4096 Jul  7 16:39 src
drwxrwxr-x 2 brian brian 4096 Jul  7 16:39 tests
-rw-rw-r-- 1 brian brian    6 Jul  7 16:39 VERSION

```

5. I presume that as a consequence, I am unable to run “make” because there is no “Makefile”.

Looking forward to trying libcsp.

**Comment by yann-shi** [comment]
Hi,

I'm really sorry for replying late. Please download [libcsp-0.0.1.tar.gz](https://github.com/shiyanhui/libcsp/releases/download/v0.0.1/libcsp-0.0.1.tar.gz), not `Source code (zip)` or `Source code (tar.gz)` in the [release page](https://github.com/shiyanhui/libcsp/releases).

Then follow the instructions step by step in the [Installation](https://libcsp.com/installation/) page.
